name: Discord News Bot

on:
  schedule:
    - cron: "*/5 * * * *"   # κάθε 5 λεπτά
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install packages
        run: npm install

      - name: Run bot
        run: node index.js
        env:
          TOKEN: ${{ secrets.TOKEN }}
          FINNHUB_API: ${{ secrets.FINNHUB_API }}
          NEWS_CHANNEL_ID: ${{ secrets.NEWS_CHANNEL_ID }}
